export const AUTH_ACCOUNT_LOGIN_REQUEST = 'AUTH_ACCOUNT_LOGIN_REQUEST'
export const AUTH_ACCOUNT_LOGIN_SUCCESS = 'AUTH_ACCOUNT_LOGIN_SUCCESS'
export const AUTH_ACCOUNT_LOGIN_FAIL = 'AUTH_ACCOUNT_LOGIN_FAIL'

export const AUTH_ACCOUNT_LOGOUT = 'AUTH_ACCOUNT_LOGOUT'

export const AUTH_ACCOUNT_UPDATE_PASSWORD_REQUEST = 'AUTH_ACCOUNT_UPDATE_PASSWORD_REQUEST'
export const AUTH_ACCOUNT_UPDATE_PASSWORD_SUCCESS = 'AUTH_ACCOUNT_UPDATE_PASSWORD_SUCCESS'
export const AUTH_ACCOUNT_UPDATE_PASSWORD_FAIL = 'AUTH_ACCOUNT_UPDATE_PASSWORD_FAIL'

export const AUTH_ACCOUNT_INFO_REQUEST = 'AUTH_ACCOUNT_INFO_REQUEST'
export const AUTH_ACCOUNT_INFO_SUCCESS = 'AUTH_ACCOUNT_INFO_SUCCESS'
export const AUTH_ACCOUNT_INFO_FAIL = 'AUTH_ACCOUNT_INFO_FAIL'

export const AUTH_PERMISSION_REQUEST = 'AUTH_PERMISSION_REQUEST'
export const AUTH_PERMISSION_SUCCESS = 'AUTH_PERMISSION_SUCCESS'
export const AUTH_PERMISSION_FAIL = 'AUTH_PERMISSION_FAIL'

export const AUTH_QUALIFICATION_INFO_REQUEST = 'AUTH_QUALIFICATION_INFO_REQUEST'
export const AUTH_QUALIFICATION_INFO_SUCCESS = 'AUTH_QUALIFICATION_INFO_SUCCESS'
export const AUTH_QUALIFICATION_INFO_FAIL = 'AUTH_QUALIFICATION_INFO_FAIL'

export const AUTH_VALIDATE_BRAND_REQUEST = 'AUTH_VALIDATE_BRAND_REQUEST'
export const AUTH_VALIDATE_BRAND_SUCCESS = 'AUTH_VALIDATE_BRAND_SUCCESS'
export const AUTH_VALIDATE_BRAND_FAIL = 'AUTH_VALIDATE_BRAND_FAIL'
export const AUTH_UPDATE_BRAND = 'AUTH_UPDATE_BRAND'
