export default {
  FETCH_FINANCE_LIST_FILTER: 'FETCH_FINANCE_LIST_FILTER',
  FETCH_FINANCE_LIST: 'FETCH_FINANCE_LIST',
  FETCH_FINANCE_TOTAL_AMOUNT: 'FETCH_FINANCE_TOTAL_AMOUNT',
  UPDATE_FINANCE_LIST_FILTER_VALUE: 'UPDATE_FINANCE_LIST_FILTER_VALUE',
  RESET_FINANCE_LIST_FILTER_VALUE: 'RESET_FINANCE_LIST_FILTER_VALUE',
  UPDATE_FINANCE_LIST: 'UPDATE_FINANCE_LIST',
  UPDATE_FINANCE_LIST_SPLIT_PO: 'UPDATE_FINANCE_LIST_SPLIT_PO',
  RESET_FINANCE_LIST: 'RESET_FINANCE_LIST',
  FETCH_FINANCE_CLIENT_AND_SUPPLIER_LIST: 'FETCH_FINANCE_CLIENT_AND_SUPPLIER_LIST',
}
