export const HOME_DATA_REQUEST = 'HOME_DATA_REQUEST'
export const HOME_DATA_SUCCESS = 'HOME_DATA_SUCCESS'
export const HOME_DATA_FAIL = 'HOME_DATA_FAIL'

export const TASK_OPTIONS_REQUEST = 'TASK_OPTIONS_REQUEST'
export const TASK_OPTIONS_SUCCESS = 'TASK_OPTIONS_SUCCESS'
export const TASK_OPTIONS_FAIL = 'TASK_OPTIONS_FAIL'

export const HOME_DATA_ITEM_UPDATE_REQUEST = 'HOME_DATA_ITEM_UPDATE_REQUEST'
export const HOME_DATA_ITEM_UPDATE_SUCCESS = 'HOME_DATA_ITEM_UPDATE_SUCCESS'
export const HOME_DATA_ITEM_UPDATE_FAIL = 'HOME_DATA_ITEM_UPDATE_FAIL'

