export default {
  FETCH_ORDER_LIST: 'FETCH_ORDER_LIST',
  UPDATE_ORDER_LIST_ACTIVE_TAB_KEY: 'UPDATE_ORDER_LIST_ACTIVE_TAB_KEY',
  UPDATE_ORDER_LIST_SORTER: 'UPDATE_ORDER_LIST_SORTER',
  UPDATE_ORDER_LIST: 'UPDATE_ORDER_LIST'
}
