export const FETCH_REPORT_PLATFORMS = 'FETCH_REPORT_PLATFORMS'
export const FETCH_REPORT_LIST = 'FETCH_REPORT_LIST'
export const UPDATE_REPORT_LIST_ACTIVE_TAB_KEY = 'UPDATE_REPORT_LIST_ACTIVE_TAB_KEY'
export const UPDATE_REPORT_LIST_PARAMS = 'UPDATE_REPORT_LIST_PARAMS'
export const RESET_REPORT_LIST = 'RESET_REPORT_LIST'

export const FETCH_REPORT_INFO = 'FETCH_REPORT_INFO'
export const FETCH_REPORT_INTERACTIVE_TRENDS = 'FETCH_REPORT_INTERACTIVE_TRENDS'
export const FETCH_REPORT_HOT_WORDS = 'FETCH_REPORT_HOT_WORDS'
export const FETCH_REPORT_HOT_COMMENTS = 'FETCH_REPORT_HOT_COMMENTS'
export const FETCH_REPORT_COMMENT_MOOD = 'FETCH_REPORT_COMMENT_MOOD'

export const UPDATE_REPORT_INFO_DATE_RANGE = 'UPDATE_REPORT_INFO_DATE_RANGE'
