// 达人报价列表
// import util from './util'
// const list = [
//   'FETCH_PLATFORMS',
// ]

// export default util(list, 'TALENT_LIST')

export default {
  TALENT_LIST_FETCH_PLATFORMS: 'TALENT_LIST_FETCH_PLATFORMS',
  FETCH_TALENT_LIST_FILTER_MAP: 'FETCH_TALENT_LIST_FILTER_MAP',
  UPDATE_TALENT_LIST_ACTIVE_TAB_KEY: 'UPDATE_TALENT_LIST_ACTIVE_TAB_KEY',
  UPDATE_TALENT_LIST_FILTER_VALUE: 'UPDATE_TALENT_LIST_FILTER_VALUE',
  RESET_TALENT_LIST_VALUE: 'RESET_TALENT_LIST_VALUE',
  FETCH_TALENT_LIST: 'FETCH_TALENT_LIST',
  UPDATE_TALENT_LIST: 'UPDATE_TALENT_LIST',
  UPDATE_NEW_TALENT_VALUE: 'UPDATE_NEW_TALENT_VALUE',
  RESET_NEW_TALENT_VALUE: 'RESET_NEW_TALENT_VALUE',
  CLEAR_TALENT_VALUE: 'CLEAR_TALENT_VALUE',
  UPDATE_TALENT_LIST_SELECTED_ROWS: 'UPDATE_TALENT_LIST_SELECTED_ROWS',
  FETCH_TALENT_CART_ID_LIST: 'FETCH_TALENT_CART_ID_LIST',
  UPDATE_TALENT_CART_LIST: 'UPDATE_TALENT_CART_LIST',
  CLEAR_TALENT_SELECT: 'CLEAR_TALENT_SELECT',
  UPDATE_TALENT_LIST_SORTER: 'UPDATE_TALENT_LIST_SORTER',
  FETCH_TALENT_FORM_LIST_DATA: 'FETCH_TALENT_FORM_LIST_DATA',
  FETCH_TALENT_LIST_CART_INFO: 'FETCH_TALENT_LIST_CART_INFO',
  REMOVE_TALENT_IN_CART_LIST: 'REMOVE_TALENT_IN_CART_LIST',
  UPDATE_TALENT_LIST_KEYWORDS: 'UPDATE_TALENT_LIST_KEYWORDS',
  RESET_TALENT_LIST: 'RESET_TALENT_LIST',
}
