/**
 * Default development API config.
 * 根据/src/lib/request中对api的解析规则
 * apiList子key的值为对象集合
 * 且key不能为`js`, `json`, `ts`中的一种
 */
import project from '../config/project'

const { host, port } = project

let BASE_URL = `http://${host}:${port.mock}/`
// let BASE_URL = `http://192.168.1.62:${project.port.mock}/`
if (process.env.NODE_ENV === 'production') {
  // BASE_URL = `http://61.174.52.49:${project.port.mock}`
  BASE_URL = `http://${host}:${port.mock}/`
}
export default {
  apiBaseUrl: BASE_URL,
  yApiBaseUrl: 'http://61.174.52.49:9400/mock/20/',
  uploadFile: 'https://testkolapi.mdfull.com/file/add', // 上传
  // uploadFile: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
  downloadFile: '',
  tokenName: 'vra-token',
  apiList: {
    common: {
      tips: '~/tips',
      updateFileRemark: 'common/common.json?api=common.updateFileRemark',
    },
    map: {
      accountStatus: 'map/accountStatus.json',
    },
    auth: {
      login: 'auth/login.json',
      accountInfo: 'auth/accountInfo.json',
      changePassword: 'common/common.json?api=auth.changePassword',
      permissionList: 'auth/permissionList.json',

      getCode: 'auth/getCode.json',
      validateCode: 'auth/validateCode.json',
      signup: 'common/common.json?api=auth.signup',
      resetPassword: 'common/common.json?api=auth.resetPassword',
      validateAccount: 'common/common.json?api=auth.validateAccount',
      getQualificationInfo: 'auth/getQualificationInfo.json',
      validateBrand: 'auth/validateBrand.json',
    },
    notice: {
      list: 'notice/list.json',
      read: 'common/common.json?api=notice.read',
      delete: 'common/common.json?api=notice.delete',
    },
    home: {
      index: 'home/index.json?env=development',
      submit: 'home/submit.json',
    },
    admin: {
      audit: {
        agentAuditInfo: 'admin/audit/agent-audit-info.json',
        agentAuditSubmit: 'common/common.json?api=admin.audit.agentAuditSubmit',
        agentCertificateExample: BASE_URL + 'image/agentCertificateExample.jpg',
      },
      brand: {
        brandApplyList: 'admin/brand/brand-apply-list.json',
        brandApplyInfo: 'admin/brand/brand-apply-info.json',
        brandApplySubmit: 'common/common.json?api=admin.brand.brandApplySubmit',
        industryCategoryList: 'admin/brand/industry-category-list.json',
        brandCertificateExample: BASE_URL + 'image/brandCertificateExample.jpg',
      },
      account: {
        accountList: 'admin/account/account-list.json',
        accountEnable: 'common/common.json?api=admin.account.accountEnable',
        accountSubmit: 'common/common.json?api=admin.account.accountSubmit',
      },
      // schedule: {
      //   campaignList: 'operator/schedule/campaign-list.json',
      //   productList: 'operator/schedule/product-list.json',
      //   campaignCount: 'operator/schedule/campaign-count.json',
      //   platformTalentList: 'operator/schedule/platform-talent-list.json',
      //   customerConfirmInfo: 'operator/schedule/customer-confirm-info.json',
      //   customerConfirmAuditInfo: 'operator/schedule/customer-confirm-audit-info.json',
      //   customerConfirmAuditSubmit: 'common/common.json?api=schedule.schedule.customerConfirmAuditSubmit',
      //   auditAcceptSubmit: 'common/common.json?api=admin.schedule.auditAcceptSubmit',
      //   auditRejectSubmit: 'common/common.json?api=admin.schedule.auditRejectSubmit',
      //   auditFinishSubmit: 'common/common.json?api=admin.schedule.auditFinishSubmit',
      //   rejectReasonList: 'operator/schedule/reject-reason-list.json',
      //   confirmReasonList: 'operator/schedule/confirm-reason-list.json',
      //   auditHistoryList: 'operator/schedule/audit-history-list.json',
      //   auditHistoryTotalInfo: 'operator/schedule/audit-history-total-info.json',
      //   auditHistoryTalentList: 'operator/schedule/audit-history-talent-list.json',
      //   platformStat: 'operator/schedule/platform-stat.json',
      //   totalStat: 'operator/schedule/total-stat.json',
      //   internalPreview: 'operator/schedule/internal-preview.json',
      //   internalPreviewCount: 'operator/schedule/internal-preview-count.json',
      //   scheduleExport: 'common/common.json?api=admin.schedule.scheduleExport',
      // },
      institute: {
        instituteFilter: 'institute/institute-filter.json',
        instituteList: 'institute/institute-list.json',
        instituteInfo: 'institute/institute-info.json',
        instituteTalentList: 'institute/institute-talent-list.json',
        rebateSubmit: 'common/common.json?api=admin.institute.rebateSubmit',
        updateAgencyRebate: 'common/common.json?api=admin.institute.updateAgencyRebate',
      },
    },
    operator: {
      brand: {
        brandList: 'operator/brand/brand-list.json',
        brandInfo: 'operator/brand/brand-info.json',
        getImportPlatforms: 'operator/brand/importPlatforms.json',
        validateImport: 'operator/brand/validateImport.json',
        import: 'common/common.json?api=operator.brand.import',
        templateFileUrl: 'https://docs.weiquaninfo.cn/gitbook/assets/kol/files/account/douyin.csv',
        templateFileUrl1: 'common/common.json?key1',
        templateFileUrl2: 'common/common.json?key2',
        templateFileUrl3: 'common/common.json?key3',
        templateFileUrl4: 'common/common.json?key4',
        templateFileUrl5: 'common/common.json?key5',
        templateFileUrl6: 'common/common.json?key6',
        templateFileUrl7: 'common/common.json?key7',
        templateFileUrl8: 'common/common.json?key8',
        templateFileUrl9: 'common/common.json?key9',
        templateFileUrl10: 'common/common.json?key10',
      },
      schedule: {
        campaignList: 'operator/schedule/campaign-list.json',
        draftList: 'operator/schedule/draft-list.json',
        productList: 'operator/schedule/product-list.json',
        campaignCount: 'operator/schedule/campaign-count.json',
        platformTalentList: 'operator/schedule/platform-talent-list.json',
        customerConfirmInfo: 'operator/schedule/customer-confirm-info.json',
        customerConfirmSubmit: 'common/common.json?api=operator.schedule.customerConfirmSubmit',
        saveDraftSubmit: 'common/common.json?api=operator.schedule.saveDraftSubmit',
        auditSubmit: 'common/common.json?api=operator.schedule.auditSubmit',
        removeTalentSubmit: 'common/common.json?api=operator.schedule.removeTalentSubmit',
        auditHistoryList: 'operator/schedule/audit-history-list.json',
        auditHistoryTotalInfo: 'operator/schedule/audit-history-total-info.json',
        auditHistoryTalentList: 'operator/schedule/audit-history-talent-list.json',
        platformStat: 'operator/schedule/platform-stat.json',
        totalStat: 'operator/schedule/total-stat.json',
        internalPreview: 'operator/schedule/internal-preview.json',
        internalPreviewCount: 'operator/schedule/internal-preview-count.json',
        externalPreview: 'operator/schedule/external-preview.json',
        scheduleExport: 'common/common.json?api=operator.schedule.scheduleExport',
        scheduleImport: 'common/common.json?api=operator.schedule.scheduleImport',
        validateImport: 'operator/schedule/validateImport.json',
        addTalent: 'common/common.json?api=operator.schedule.addTalent',
        getOrderInfo: 'operator/schedule/order-info.json',
        getOrderInfoTalentList: 'operator/schedule/order-info-talent-list.json',
      },
      cart: {
        cartInfo: 'operator/cart/cart-info.json',
        platformTalentList: 'operator/cart/platform-talent-list.json',
        removeTalentSubmit: 'common/common.json?api=operator.cart.removeTalentSubmit',
        expectedDataRequired: 'common/common.json?api=operator.cart.expectedDataRequired',
        expectedDataSubmit: 'common/common.json?api=operator.cart.expectedDataSubmit',
        expectedDataSubmitBatch: 'common/common.json?api=operator.cart.expectedDataSubmitBatch',
        generateScheduleSubmit: 'common/common.json?api=operator.cart.generateScheduleSubmit',
        productList: 'operator/cart/product-list.json',
        productEditSubmit: 'common/common.json?api=operator.cart.productEditSubmit',
        productRemoveSubmit: 'common/common.json?api=operator.cart.productRemoveSubmit',
      },
      talent: {
        getPlatforms: 'report/plateforms.json',
        getFilterMap: 'talent/getFilterMap.json',
        getList: '~/talent/getList',
        updateList: 'common/common.json?api=operator.talent.updateList',
        getLockPrice: 'talent/getLockPrice.json',
        getAllTags: 'talent/getAllTags.json',
        getTalentInfo: 'talent/getTalentInfo.json',
        add: 'common/common.json?api=operator.talent.add',
        bulkUpdate: 'common/common.json?api=operator.talent.bulkUpdate',
        talentHistoricalCost: 'operator/talent-analysis/talent-cost.json',
        platformHistoricalQuote: 'operator/talent-analysis/platform-quote.json',
        cooperationAnalysis: 'operator/talent-analysis/cooperation-analysis.json',
        getScheduleList: 'talent/getScheduleList.json',
        addSchedule: 'common/common.json?api=operator.talent.addSchedule',
        getCartIdList: 'talent/getCartIdList.json',
        updateCartList: 'common/common.json?api=operator.talent.updateCartList',
        delete: 'common/common.json?api=operator.talent.delete',
        getFormListData: 'talent/getFormListData.json',
        applyChangeFrame: '~/talent/changeFrame',
        changeFrame: '~/talent/changeFrame',
      },
      order: {
        getList: 'order/getList.json',
        getTalentList: 'order/getTalentList.json',
        talentPublish: 'common/common.json?api=operator.order.talentPublish',
        delete: 'common/common.json?api=operator.order.delete',
        getScheduleTalents: 'order/getScheduleTalents.json',
        add: 'common/common.json?.api=operator.order.add',
        getInfo: 'order/getInfo.json',
        edit: 'common/common.json?.api=operator.order.edit',
        update: 'common/common.json?.api=operator.order.update',
      },
    },
    audit: {
      agent: {
        tabs: 'audit/tabs.json',
        list: 'audit/agentList.json',
        getQualificationInfo: 'audit/getAgentQualificationInfo.json',
        audit: 'common/common.json?api=audit.agent.audit',
        getRefuseReason: 'audit/getAgentRefuseReason.json',
      },
      brand: {
        tabs: 'audit/tabs.json',
        list: 'audit/brandList.json',
        getQualificationInfo: 'audit/getBrandQualificationInfo.json',
        audit: 'common/common.json?api=audit.brand.audit',
        getRefuseReason: 'audit/getBrandRefuseReason.json',
      },
    },
    report: {
      getPlatforms: 'report/plateforms.json',
      list: 'report/list.json',
      getTalentByProject: '~/report/get-talent',
      getProjectByTalent: 'report/getProjectByTalent.json',
      info: 'report/info_douyin.json',
      interactiveTrends: 'report/interactiveTrends_bili.json',
      hotWords: 'report/hotWords.json',
      hotComments: 'report/hotComments.json',
      productComments: 'report/hotComments.json?api=report.productComments',
      negativeComments: 'report/hotComments.json?api=report.negativeComments',
      commentMood: 'report/commentMood.json',
      viewRateTrends: 'report/viewTimeTrends.json',
      export: '~/report/export',
    },
    finance: {
      filterMap: 'finance/filterMap.json',
      list: 'finance/list.json',
      totalAmount: 'finance/totalAmount.json',
      update: 'common/common.json?api=finance.update',
    },
    competitor: {
      xiaohongshuList: '~/competitor/xiaohongshuList',
      addXiaohongshuKeywords: '~/competitor/addXiaohongshuKeywords',
      removeXiaohongshuKeywords: '~/competitor/removeXiaohongshuKeywords',
      keywordsInfo: '~/competitor/keywordsInfo',
      articleList: '~/competitor/articleList',
      export: '~/competitor/export',
      applyXiaohongshuKeywords: '~/competitor/applyXiaohongshuKeywords',
      overviewInfo: '~/competitor/overviewInfo',
      overviewTotal: '~/competitor/overviewTotal',
      overviewBrand: '~/competitor/overviewBrand',
      compare: 'competitor/compare.json',
    },
    progress: {
      template: '~/progress/template',
      updateTemplate: '~/progress/updateTemplate',
      allForms: '~/progress/allForms',
      addTemplate: '~/progress/addTemplate',
      filterOrderList: '~/progress/filterOrderList',
      orderInfo: '~/progress/orderInfo',
      filterTalentList: '~/progress/filterTalentList',
      filterAgencyList: '~/progress/filterAgencyList',
      filterProductList: '~/progress/filterProductList',
      addTask: '~/progress/addTask',
      list: 'progress/list.json',
      finish: '~/progress/finish',
      delete: '~/progress/delete',
      deleteLog: '~/progress/deleteLog',
      getDiff: '~/progress/getDiff',
      update: '~/progress/update',
      info: 'progress/info.json',
      exportOverview: 'common/common.json?api=progress.exportOverview',
      getTaskCounts: '~/progress/counts',
      updateAE: '~/progress/updateAE',
      getStepPreset: '~/progress/getStepPreset',
      updateStepPreset: '~/progress/updateStepPreset',
      delay: '~/progress/delay',
      logList: '~/progress/logList',
      confirmDate: '~/progress/confirmDate',
      taskManage: '~/progress/taskManage',
      addTalent: '~/progress/addTalent',
      delayInfo: '~/progress/delayInfo',
      terminateInfo: '~/progress/terminateInfo',
      confirmTerminate: '~/progress/confirmDate',
    },
    project: {
      productList: 'operator/schedule/product-list.json',
      list: '~/project/list',
      memberList: '~/project/member/list', // 品牌下所有用户
      // initialMembers: 'project/initial_members.json',
      // confirmedMembers: 'project/confirmed_members.json',
      // editMembers: '~/project/member/edit',
      createProject: '~/project/create',
      audit: '~/project/audit',
      setBeforeSteps: '~/project/setBeforeSteps',
      updateStep: '~/project/updateStep',
      beginStep: '~/project/beginStep',
      clockInfo: '~/project/clockInfo',
      clock: '~/project/clock',
      addTalentTimeline: '~/project/addTalentTimeline',
      importTalentTimeline: '~/project/importTalentTimeline',
      talentTimelineTemplateLink: 'talentTimelineTemplateLink',
      talentTimelineDownloadLink: '~/project/talentTimelineDownloadLink',
      generateProgress: '~/project/generateProgress',
      createProjectUserList: '~/project/createProjectUserList',
      projectTypeList: '~/project/getProjectTypeList',
      // showProjectMembers: 'project/projectMembers.json',
      // showProjectMembers: '~/project/showProjectMembers',
      editProjectMembers: '~/project/editProjectMembers', // 项目成员编辑提交
      getOrganizationData: 'project/organizationData.json', // 项目组织结构数据，和编辑成员提交的数据一致
      getDivisionList: 'project/getDivisionList.json', // 项目分工
      getUserList: '~/project/getUserList', // 取项目成员及角色
      // 2021-06-01更新
      clockInfoHistory: '~/project/clockInfoHistory',
      // 2021-06-03更新
      updateProject: 'common/common.json',

      // 2021-06-21
      newInfo: '~/project/newInfo', // 项目更新提交数据
      confirmUpdate: 'common/common.json?api=project.confirmUpdate',

      leaderCancelProject: '~/project/leaderCancelProject', // 项目负责人申请取消项目
      confirmProjectCancel: '~/project/confirmProjectCancel', // QC人及CEO确认项目取消

      // 2021-07-16
      财务节点内收入和成本列表: '~/project/financeInfo',
      // 财务节点内收入和成本更新: '~/project/financeInfoUpdate', // 新增、编辑和删除
      财务节点内收入和成本提交: '~/project/financeInfoSubmit',
      CEO确认财务收入和成本: '~/project/clock',
      项目开票收入和成本列表: '~/project/invoiceInfo',
      收入申请开票: '~/project/incomeInvoice',
      收入开票审核: '~/project/incomeInvoiceAudit',
      收入确认开票: '~/project/incomeInvoiceConfirmed',
      收入确认回款: '~/project/incomeInvoicePayback',
      开票操作记录: '~/project/invoiceLog',
      删除开票申请: '~/project/deleteApplyInvoice',
    },
    发票: {
      列表: '~/invoice/list',
      新增: '~/invoice/add',
      编辑: '~/invoice/update', // 比新增仅多一个id字段
      删除: '~/invoice/delete',
    },
    dashboard: {
      totalCount: '~/dashboard/totalCount',
      projectList: '~/dashboard/projectList',
      myPending: '~/dashboard/myPending',
      beforeInfo: '~/dashboard/beforeInfo',
      goingInfo: '~/dashboard/goingInfo',
      afterInfo: '~/dashboard/afterInfo',
      finishedInfo: '~/dashboard/finishedInfo',
    },
    organization: {
      organizationList: 'organization/organizationList.json',
      userList: 'organization/userList.json',
      updateNode: 'common/common.json',
    },
    媒体: {
      列表: '~/media/list',
      新增: '~/media/add',
      编辑: '~/media/update', // 比新增仅多一个id字段
      删除: '~/media/delete',
    },
  },
}
