/**
 * Default predev API config.
 * 根据/src/lib/request中对api的解析规则
 * apiList子key的值为对象集合
 * 且请求path中不能有小数点
 */

const BASE_URL = 'https://testkolapi.mdfull.com'
// const BASE_URL = 'http://kolapi.mdfull.com'
// const BASE_URL = 'http://localhost:8112'
export default {
  apiBaseUrl: BASE_URL,
  yApiBaseUrl: 'http://61.174.52.49:9400/mock/20/',
  uploadFile: `${BASE_URL}/file/add`, // 上传
  // uploadFile: 'http://61.174.52.49:9400/mock/20/file/add',
  downloadFile: '',
  tokenName: 'vra-token',
  apiList: {
    common: {
      tips: 'tip/list',
      updateFileRemark: 'file/add-remark',
    },
    map: {
      accountStatus: 'auth/get-audit-status',
    },
    auth: {
      login: 'auth/login',
      accountInfo: 'home/get-user-info',
      changePassword: 'home/change-password',
      permissionList: 'home/get-permissions',
      getCode: 'auth/get-code',
      validateCode: 'auth/verify-code',
      signup: 'auth/registe',
      resetPassword: 'user/reset-password',
      validateAccount: 'user/validate-account',
      getQualificationInfo: 'agent-file/get-info',
      validateBrand: 'brand/validate',
    },
    notice: {
      list: 'system/notice-list',
      read: 'system/read-notice',
      delete: 'system/delete-notice',
    },
    home: {
      index: 'home/index?env=development',
      submit: 'home/submit.json',
    },
    admin: {
      audit: {
        agentAuditInfo: 'audit/admin-agent-audit-info',
        agentAuditSubmit: 'audit/admin-agent-audit-save',
        agentCertificateExample: BASE_URL + '/image/agent_certificate_example.jpeg',
      },
      brand: {
        brandApplyList: 'brand/get-list',
        brandApplyInfo: 'brand/get-info',
        brandApplySubmit: 'brand/save',
        industryCategoryList: 'brand-category/list',
        brandCertificateExample: BASE_URL + '/image/brand_certificate_example.jpeg',
      },
      account: {
        accountList: 'user/get-agent-user-list',
        accountEnable: 'user/enable-agent-user',
        accountSubmit: 'user/save-agent-user',
      },
      schedule: {
        campaignList: 'schedule/get-list',
        productList: 'schedule/product-line-list',
        campaignCount: 'schedule/get-count',
        platformTalentList: 'schedule/platform-talent-list',
        customerConfirmInfo: 'schedule/customer-confirm-info',
        customerConfirmAuditInfo: 'schedule/customer-confirm-audit-info',
        customerConfirmAuditSubmit: 'schedule/customer-confirm-audit-save',
        removeTalentSubmit: 'schedule/remove-talent',
        auditAcceptSubmit: 'schedule/audit-accept',
        auditRejectSubmit: 'schedule/audit-reject',
        auditFinishSubmit: 'schedule/audit-finish',
        rejectReasonList: 'schedule/reject-reason-list',
        confirmReasonList: 'schedule/confirm-reason-list',
        auditHistoryList: 'schedule/audit-history-list',
        auditHistoryTotalInfo: 'schedule/audit-history-total-info',
        auditHistoryTalentList: 'schedule/audit-history-talent-list',
        platformStat: 'schedule/platform-stat',
        totalStat: 'schedule/total-stat',
        internalPreview: 'schedule/internal-preview',
        internalPreviewCount: 'schedule/internal-preview-count',
        externalPreview: 'schedule/external-preview',
        scheduleExport: 'schedule/export',
      },
      institute: {
        instituteFilter: 'mcn/get-platform-dim',
        instituteList: 'mcn/get-list',
        instituteInfo: 'mcn/get-info',
        instituteTalentList: 'mcn/get-talent-list',
        rebateSubmit: 'mcn/update-rebate',
        updateAgencyRebate: 'mcn/update-mcn-rebate',
      },
    },
    operator: {
      brand: {
        brandList: 'brand/get-list',
        brandInfo: 'brand/get-info',
        getImportPlatforms: 'platform/get-list',
        validateImport: 'talent/validate',
        import: 'talent/import',
        templateFileUrl1: 'file/get?fileId=8',
        templateFileUrl2: 'file/get?fileId=9',
        templateFileUrl3: 'file/get?fileId=10',
        templateFileUrl4: 'file/get?fileId=11',
        templateFileUrl5: 'file/get?fileId=12',
        templateFileUrl6: 'common/common.json?key6',
        templateFileUrl7: 'common/common.json?key7',
        templateFileUrl8: 'common/common.json?key8',
        templateFileUrl9: 'common/common.json?key9',
        templateFileUrl10: 'common/common.json?key10',
      },
      schedule: {
        campaignList: 'project/get-list',
        draftList: 'project/get-draft-list',
        productList: 'project/product-line-list',
        campaignCount: 'project/get-count',
        platformTalentList: 'project/platform-talent-list',
        customerConfirmInfo: 'project/customer-confirm-info',
        customerConfirmSubmit: 'project/customer-confirm-save',
        saveDraftSubmit: 'project/draft-save',
        auditSubmit: 'project/audit-save',
        removeTalentSubmit: 'project/remove-talent',
        auditHistoryList: 'project/audit-history-list',
        auditHistoryTotalInfo: 'project/audit-history-total-info',
        auditHistoryTalentList: 'project/audit-history-talent-list',
        platformStat: 'project/platform-stat',
        totalStat: 'project/total-stat',
        internalPreview: 'project/internal-preview',
        internalPreviewCount: 'project/internal-preview-count',
        externalPreview: 'project/external-preview',
        scheduleExport: 'project/export',
        scheduleImport: 'project/import',
        validateImport: 'project/validate-import',
        addTalent: 'project/add-talent',
        getOrderInfo: 'project/get-project-info',
        getOrderInfoTalentList: 'project/get-project-talent-info',
      },
      cart: {
        cartInfo: 'cart/info',
        platformTalentList: 'cart/platform-talent-list',
        removeTalentSubmit: 'cart/remove-talent',
        expectedDataRequired: 'cart/expected-data-required',
        expectedDataSubmit: 'cart/expected-data-save',
        expectedDataSubmitBatch: 'cart/expected-data-save-batch',
        generateScheduleSubmit: 'cart/generate-project',
        productList: 'project-line/list',
        productEditSubmit: 'project-line/save',
        productRemoveSubmit: 'project-line/remove',
        scheduleExport: 'common/common.json?api=operator.schedule.scheduleExport',
      },
      talent: {
        getPlatforms: 'platform/get-list',
        getFilterMap: 'talent/get-dims',
        getList: 'talent/get-list',
        updateList: 'talent/update',
        getLockPrice: 'talent/get-lock-price-list',
        getAllTags: 'talent/get-tags',
        getTalentInfo: 'talent/get-info',
        add: 'talent/add',
        bulkUpdate: 'talent/batch-update',
        talentHistoricalCost: 'talent/talent-cost-history',
        platformHistoricalQuote: 'talent/platform-quote-history',
        cooperationAnalysis: 'talent/cooperation-history',
        getScheduleList: 'talent/get-schedule-list',
        addSchedule: 'talent/add-schedule-talent',
        getCartIdList: 'cart/get-talent-list',
        updateCartList: 'cart/update-talent-list',
        delete: 'talent/delete',
        getFormListData: 'talent/get-talent-form-list',
        applyChangeFrame: 'talent/apply-change-frame',
        changeFrame: 'talent/change-frame',
      },
      order: {
        getList: 'project/get-order-list',
        getTalentList: 'project/get-talent-list',
        talentPublish: 'project/publish',
        delete: 'project/delete',
        getScheduleTalents: 'project/get-schedule-talent',
        add: 'project/add',
        getInfo: 'project/get-order-info',
        edit: 'project/update',
        update: 'project/update',
      },
    },
    audit: {
      agent: {
        tabs: 'agent-file/statistics',
        list: 'agent-file/list',
        getQualificationInfo: 'agent-file/get-info',
        audit: 'agent-file/audit',
        getRefuseReason: 'audit-comment/brief',
      },
      brand: {
        tabs: 'brand/statistics',
        list: 'brand/audit-list',
        getQualificationInfo: 'brand/audit-info',
        audit: 'brand/audit',
        getRefuseReason: 'audit-comment/brief',
      },
    },
    report: {
      getPlatforms: 'platform/get-list',
      list: 'project/get-post-list',
      getTalentByProject: 'project/get-talent',
      getProjectByTalent: 'project/get-project',
      info: 'project/info',
      interactiveTrends: 'project/trend',
      hotWords: 'project/wordcloud',
      hotComments: 'project/comment',
      productComments: 'project/keyword-comment',
      negativeComments: 'project/negative-comment',
      commentMood: 'project/comment-attitude',
      viewRateTrends: 'project/play-distribution',
      export: 'project/export-post',
    },
    finance: {
      filterMap: 'finance/get-status-dim',
      list: 'finance/list',
      totalAmount: 'finance/get-total-amount',
      update: 'finance/save',
    },
    competitor: {
      xiaohongshuList: 'xiaohongshu-search-stats/get-list',
      addXiaohongshuKeywords: 'brand-key/add',
      removeXiaohongshuKeywords: 'brand-key/remove',
      keywordsInfo: 'xiaohongshu-search-stats/get',
      articleList: 'xiaohongshu-search-post/get-list',
      export: 'xiaohongshu-search-post/export',
      applyXiaohongshuKeywords: 'brand-key/apply',
      overviewInfo: 'xiaohongshu-search-post/get-brand-list',
      overviewTotal: 'xiaohongshu-search-post/get-overview-total',
      overviewBrand: 'xiaohongshu-search-post/get-overview-brand',
      compare: 'xiaohongshu-search-post/get-compare-data',
    },
    progress: {
      template: 'agenda-template/get-list',
      updateTemplate: 'agenda-template/save',
      allForms: 'platform/get-form-list',
      addTemplate: 'agenda-template/save',

      // filterOrderList: 'progress-project/get-available-project',
      // orderInfo: 'progress-project/get-available-project-talent',

      filterTalentList: 'agenda-talent/get-search-talent-list',
      filterAgencyList: 'agenda-talent/get-mcn-list',
      filterProductList: 'project-line/list',

      // addTask: 'progress-project/save',

      finish: 'agenda-talent-step/finish',
      delete: 'agendat-talent/remove',

      // deleteLog: 'progress-project-talent/get-remove-list',
      // getDiff: 'progress-project-talent/get-diff-list',
      // update: 'progress-project/save',

      info: 'agenda-talent/get-info',
      exportOverview: 'agenda-talent/export-stats',
      getTaskCounts: 'agenda-talent/get-ongoing-count',
      updateAE: 'agenda-talent/update-ae',

      list: 'agenda-talent/get-list',
      getStepPreset: 'agenda-talent-step/get-preset',
      updateStepPreset: 'agenda-talent-step/save-preset',
      delay: 'agenda-talent/postpone',
      logList: 'agenda-log/get-list',
      confirmDate: 'agenda-talent/confirm-step-date-change',
      taskManage: 'agenda-talent/manage',
      addTalent: 'agenda/save-talent',
      delayInfo: 'agenda-talent/get-step-date-change',

      terminateInfo: 'agenda-talent/get-terminate-info',
      confirmTerminate: 'agenda-talent/confirm-terminate',
    },
    project: {
      productList: 'agenda/get-product-list',
      list: 'agenda/get-list',
      memberList: 'agenda/get-member-list',

      initialMembers: 'agenda/get-initial-members',
      confirmedMembers: 'agenda/get-confirmed-members',
      editMembers: 'agenda/save-member-set',

      createProject: 'agenda/save',
      audit: 'agenda/audit',
      setBeforeSteps: 'agenda/save-scheme-step',
      updateStep: 'agenda/update-step',
      beginStep: 'agenda-step/start',
      clockInfo: 'agenda/get-step-clock-info',
      clock: 'agenda-step-sign/clock-in',

      addTalentTimeline: 'agenda/save-talent',
      importTalentTimeline: 'agenda/import-talent',
      talentTimelineTemplateLink: 'talentTimelineTemplateLink',
      talentTimelineDownloadLink: 'agenda/export-talent',
      generateProgress: 'agenda/generate-progress',

      createProjectUserList: 'brand/get-agenda-create-user-list',
      projectTypeList: 'agenda-scheme/get-list',
      // projectTypeList: '~/project/getProjectTypeList',
      // showProjectMembers: 'agenda/get-crew-department',
      // showProjectMembers: '~/project/showProjectMembers',
      editProjectMembers: 'agenda/add-crew',
      // getUserList: 'agenda/get-crew-list',
      getOrganizationData: 'agenda/get-crew', // 项目组织结构数据，和编辑成员提交的数据一致
      // getOrganizationData: '~/test/agenda/get-crew',
      getDivisionList: 'agenda/get-step-user', // 项目分工
      getUserList: 'agenda/get-user-list', // 取项目成员及角色
      clockInfoHistory: 'agenda-step/get-qc-list',
      updateProject: 'agenda/ready-update',

      newInfo: 'agenda/get-update-info', // 项目更新提交数据
      confirmUpdate: 'agenda/confirm-update',

      leaderCancelProject: 'agenda/cancel', // 项目负责人申请取消项目
      confirmProjectCancel: 'agenda/confirm-cancel', // QC人及CEO确认项目取消

      // 取项目节点，在新建项目第二步
      projectStepList: 'agenda/get-steps',

      // 2021-07-16
      财务节点内收入和成本列表: 'agenda/get-finance-info',
      //  * ↓↓ 已弃用 DEPRECATED WARNING ↓↓ * //
      // 财务节点内收入和成本更新: '~/project/financeInfoUpdate', // 新增、编辑和删除
      // 财务节点内收入和成本提交: 'agenda/save-finance',
      //  * ↑↑ 已弃用 DEPRECATED WARNING ↑↑ * //
      财务节点内收入和成本提交: 'agenda/save-finance-amount',
      CEO确认财务收入和成本: 'agenda-step-sign/clock-in',
      项目开票收入和成本列表: 'agenda-invoice/get-list',
      收入申请开票: 'agenda-invoice/add-invoice',
      收入开票审核: 'agenda-invoice/audit-invoice',
      收入确认开票: 'agenda-invoice/confirm-invoice',
      收入确认回款: 'agenda-invoice/confirm-back',
      开票操作记录: 'agenda-invoice-log/get-list',
      删除开票申请: 'agenda-invoice/remove',
    },
    发票: {
      列表: 'invoice/get-list',
      新增: 'invoice/save',
      编辑: 'invoice/save', // 比新增仅多一个id字段
      删除: 'invoice/delete',
    },
    dashboard: {
      totalCount: 'agenda/get-dashboard-statistics',
      projectList: 'agenda/get-dashboard-type-statistics',
      myPending: 'agenda/get-dashboard-todo-list',
      beforeInfo: 'agenda/get-dashboard-pre-list',
      goingInfo: 'agenda/get-dashboard-running-list',
      afterInfo: 'agenda/get-dashboard-post-list',
      finishedInfo: 'agenda/get-dashboard-finished-list',
    },
    organization: {
      organizationList: 'organization/get-list',
      userList: 'organization/get-user-list',
      updateNode: 'organization/update',
    },
    媒体: {
      列表: 'media/get-list',
      新增: 'media/save',
      编辑: 'media/save', // 比新增仅多一个id字段
      删除: 'media/delete',
    },
    财务: {
      客户或供应商列表: 'client/get-list',
      新增客户或供应商: 'client/save',
      更新客户或供应商: 'client/save',
      删除客户或供应商: 'client/delete',
    },
  },
}
